trigger:
  - main
pool:
  name: Azure Pipelines
parameters:
  - name: deploymentType
    displayName: 'Select Deployment Type'
    type: string
    default: 'staging'
    values:
      - staging
      - production
      - testing
stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Deployment type selected: ${{ parameters.deploymentType }}"
      displayName: 'Run Deployment'
