trigger:
  - main

parameters:
  - name: deploymentType
    displayName: 'Select Deployment Type'
    type: string
    default: 'staging'
    values:
      - staging
      - production
      - testing

stages:
- stage: Validate
  displayName: "Validate Pipeline Configuration"
  jobs:
  - job: ValidateJob
    displayName: "Validation Job"
    steps:
    - script: |
        echo "Validating deployment type..."
        if [[ "${{ parameters.deploymentType }}" == "staging" || "${{ parameters.deploymentType }}" == "production" || "${{ parameters.deploymentType }}" == "testing" ]]; then
          echo "Deployment type '${{ parameters.deploymentType }}' is valid."
        else
          echo "Invalid deployment type: '${{ parameters.deploymentType }}'"
          exit 1
        fi
      displayName: "Validate Deployment Type"

